services:
  db:
    build: postgres
    image: sistema_sge_db
    volumes:
      - $HOME/.postgres/sistema_sge_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DBS=sistema_sge_user_db
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    stdin_open: true
    tty: true