spring:
  application:
    name: configuration-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
            search-locations: classpath:/config/{profile}
server:
  port: 8888